import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/notification_model.dart';
import '../models/payment_model.dart';
import 'notification_service.dart';
import 'local_notification_service.dart';
import 'payment_service.dart';

final gymServiceProvider = Provider((ref) => GymService());

class GymService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  CollectionReference<Map<String, dynamic>> _userGymRegistrations(String studentId) =>
      _firestore.collection('profiles').doc(studentId).collection('gymRegistrations');

  Future<void> _syncRegistrationToProfile({
    required String studentId,
    required String registrationId,
    required Map<String, dynamic> data,
  }) async {
    if (studentId.isEmpty) return;
    await _userGymRegistrations(studentId)
        .doc(registrationId)
        .set(data, SetOptions(merge: true));
  }

  /// Register a student for gym access
  Future<String> registerForGym({
    required String studentId,
    required String studentName,
    required String studentEmail,
  }) async {
    try {
      // Check if student already has an active registration
      final existingReg = await _firestore
          .collection('gymRegistrations')
          .where('studentId', isEqualTo: studentId)
          .where('status', isEqualTo: 'active')
          .limit(1)
          .get();

      if (existingReg.docs.isNotEmpty) {
        throw Exception('You already have an active gym registration');
      }
      
      final pendingReg = await _firestore
          .collection('gymRegistrations')
          .where('studentId', isEqualTo: studentId)
          .where('status', isEqualTo: 'pending_payment')
          .limit(1)
          .get();

      if (pendingReg.docs.isNotEmpty) {
        throw Exception('You already have a pending registration. Please pay the fee to continue.');
      }

      // Create new registration
      final registrationId = _firestore.collection('gymRegistrations').doc().id;
      final registrationDate = DateTime.now();
      final expiryDate = registrationDate.add(const Duration(days: 365)); // 1 year validity

      final registrationData = {
        'studentId': studentId,
        'studentName': studentName,
        'studentEmail': studentEmail,
        'status': 'pending_payment', // Requires student to pay
        'registrationDate': Timestamp.fromDate(registrationDate),
        'expiryDate': Timestamp.fromDate(expiryDate),
        'createdAt': Timestamp.fromDate(registrationDate),
        'updatedAt': Timestamp.fromDate(registrationDate),
        'id': registrationId,
      };

      await _firestore
          .collection('gymRegistrations')
          .doc(registrationId)
          .set(registrationData);
          
      await _syncRegistrationToProfile(
        studentId: studentId,
        registrationId: registrationId,
        data: registrationData,
      );

      // Generate the Gym Fee Payment Record
      final dueDate = DateTime.now().add(const Duration(days: 7));
      final payment = PaymentModel(
        id: '', // Generated by Firestore inside createPayment
        userId: studentId,
        amount: 2000.0, // Fixed gym fee
        type: PaymentType.gymFee,
        status: PaymentStatus.pending,
        description: 'Gym Registration Fee',
        dueDate: dueDate,
        metadata: {'applicationId': registrationId, 'registrationId': registrationId},
      );
      
      // Using PaymentService ensures global bank details are assigned automatically
      // and feePayments record is synced.
      final paymentId = await PaymentService().createPayment(payment);

      // Update registration with paymentId for easier lookup
      await _firestore
          .collection('gymRegistrations')
          .doc(registrationId)
          .update({'paymentId': paymentId});
      
      await _syncRegistrationToProfile(
        studentId: studentId,
        registrationId: registrationId,
        data: {'paymentId': paymentId},
      );

      // Notify User about fee generated
      try {
        final notification = NotificationModel(
          id: '',
          userId: studentId,
          title: 'Gym Fee Generated',
          message: 'Your gym registration requires fee payment. Please check your payments section.',
          type: 'challan_generated',
          isRead: false,
          createdAt: DateTime.now(),
          data: {'registrationId': registrationId},
        );
        await NotificationService().createNotification(notification);
        await LocalNotificationService.showNotification(
          id: DateTime.now().millisecondsSinceEpoch.remainder(100000),
          title: notification.title,
          body: notification.message,
        );
      } catch (_) {}

      return registrationId;
    } catch (e) {
      throw Exception('Failed to register for gym: $e');
    }
  }

  /// Get user's gym registration
  Stream<Map<String, dynamic>?> getUserRegistration(String studentId) {
    return _userGymRegistrations(studentId)
        .orderBy('createdAt', descending: true)
        .limit(1)
        .snapshots()
        .map((snapshot) {
      if (snapshot.docs.isNotEmpty) {
        final data = snapshot.docs.first.data();
        data['id'] = snapshot.docs.first.id;
        return data;
      }
      return null;
    });
  }

  /// Get all gym registrations (admin)
  Stream<List<Map<String, dynamic>>> getAllRegistrations() {
    return _firestore
        .collection('gymRegistrations')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs.map((doc) {
              final data = Map<String, dynamic>.from(doc.data());
              data['id'] = doc.id;
              return data;
            }).toList());
  }

  /// Approve gym registration (admin)
  Future<void> approveRegistration(String registrationId) async {
    try {
      final docRef = _firestore.collection('gymRegistrations').doc(registrationId);
      final doc = await docRef.get();
      final data = doc.data();

      await docRef.update({
        'status': 'active',
        'updatedAt': FieldValue.serverTimestamp(),
      });

      final studentId = data?['studentId'] as String?;
      if (studentId != null && studentId.isNotEmpty) {
        await _syncRegistrationToProfile(
          studentId: studentId,
          registrationId: registrationId,
          data: {
            'status': 'active',
            'updatedAt': FieldValue.serverTimestamp(),
          },
        );

        final notification = NotificationModel(
          id: '',
          userId: studentId,
          title: 'Gym Registration Approved',
          message: 'Your gym registration has been approved. You can now access the gym facilities.',
          type: 'gym_approved',
          isRead: false,
          createdAt: DateTime.now(),
          data: {'registrationId': registrationId},
        );
        try {
          await NotificationService().createNotification(notification);
          await LocalNotificationService.showNotification(
            id: DateTime.now().millisecondsSinceEpoch.remainder(100000),
            title: notification.title,
            body: notification.message,
          );
        } catch (_) {}
      }
    } catch (e) {
      throw Exception('Failed to approve registration: $e');
    }
  }

  /// Reject gym registration (admin)
  Future<void> rejectRegistration(String registrationId, {String? reason}) async {
    try {
      final docRef = _firestore.collection('gymRegistrations').doc(registrationId);
      final doc = await docRef.get();
      final data = doc.data();

      final updates = {
        'status': 'rejected',
        'rejectionReason': reason ?? '',
        'updatedAt': FieldValue.serverTimestamp(),
      };

      await docRef.update(updates);

      final studentId = data?['studentId'] as String?;
      if (studentId != null && studentId.isNotEmpty) {
        await _syncRegistrationToProfile(
          studentId: studentId,
          registrationId: registrationId,
          data: updates,
        );

        final message = reason != null && reason.isNotEmpty
            ? 'Your gym registration has been rejected. Reason: $reason'
            : 'Your gym registration has been rejected.';
        final notification = NotificationModel(
          id: '',
          userId: studentId,
          title: 'Gym Registration Rejected',
          message: message,
          type: 'gym_rejected',
          isRead: false,
          createdAt: DateTime.now(),
          data: {'registrationId': registrationId},
        );
        try {
          await NotificationService().createNotification(notification);
          await LocalNotificationService.showNotification(
            id: DateTime.now().millisecondsSinceEpoch.remainder(100000),
            title: notification.title,
            body: notification.message,
          );
        } catch (_) {}
      }
    } catch (e) {
      throw Exception('Failed to reject registration: $e');
    }
  }

  /// Cancel gym registration (student)
  Future<void> cancelRegistration(String registrationId) async {
    try {
      final docRef = _firestore.collection('gymRegistrations').doc(registrationId);
      final doc = await docRef.get();
      final studentId = doc.data()?['studentId'] as String?;

      final updates = {
        'status': 'cancelled',
        'updatedAt': FieldValue.serverTimestamp(),
      };

      await docRef.update(updates);

      if (studentId != null && studentId.isNotEmpty) {
        await _syncRegistrationToProfile(
          studentId: studentId,
          registrationId: registrationId,
          data: updates,
        );
      }
    } catch (e) {
      throw Exception('Failed to cancel registration: $e');
    }
  }

  /// Clear all gym registrations (admin only - sets all to rejected)
  Future<void> clearAllRegistrations() async {
    try {
      // Get all active registrations
      final registrations = await _firestore
          .collection('gymRegistrations')
          .where('status', isEqualTo: 'active')
          .get();

      // Batch update all active registrations to rejected
      final batch = _firestore.batch();
      for (final doc in registrations.docs) {
        final data = doc.data();
        final studentId = data['studentId'] as String?;
        
        // Update main collection
        batch.update(doc.reference, {
          'status': 'rejected',
          'rejectionReason': 'All registrations cleared by admin',
          'updatedAt': FieldValue.serverTimestamp(),
        });

        // Update user profile subcollection if studentId exists
        if (studentId != null && studentId.isNotEmpty) {
          final userRegRef = _userGymRegistrations(studentId).doc(doc.id);
          batch.set(userRegRef, {
            'status': 'rejected',
            'rejectionReason': 'All registrations cleared by admin',
            'updatedAt': FieldValue.serverTimestamp(),
          }, SetOptions(merge: true));
        }
      }

      await batch.commit();
    } catch (e) {
      throw Exception('Failed to clear gym registrations: $e');
    }
  }
}


