import 'package:flutter/foundation.dart';
import 'dart:convert';
import 'package:cross_file/cross_file.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/hostel_model.dart';
import 'cloudinary_service.dart';

// Conditional import for dart:io (only available on non-web platforms)
import 'pdf_challan_service_io.dart'
    if (dart.library.html) 'pdf_challan_service_web.dart' as platform;

/// Service for generating and managing fee challans
class PdfChallanService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Generate a PDF challan for a hostel application
  /// Returns the URL of the generated challan
  Future<String> generateFeeChallan({
    required HostelApplicationModel application,
    required String studentName,
    required String studentEmail,
    required String arnRollNumber,
    required String bankName,
    required String accountNumber,
    required String accountTitle,
  }) async {
    try {
      // Create challan data
      final challanData = {
        'applicationId': application.id,
        'studentId': application.studentId,
        'studentName': studentName,
        'studentEmail': studentEmail,
        'arnRollNumber': arnRollNumber,
        'roomType': application.roomType.toString().split('.').last,
        'feeAmount': application.feeAmount,
        'bankName': bankName,
        'accountNumber': accountNumber,
        'accountTitle': accountTitle,
        'dueDate':
            DateTime.now().add(const Duration(days: 7)).toIso8601String(),
        'generatedAt': DateTime.now().toIso8601String(),
        'status': 'pending',
      };

      // For now, we'll create a text-based challan and upload it
      // In production, you would use a PDF generation library like pdf or printing
      final challanText = _generateChallanText(challanData);

      final challanId = application.id;

      // Save challan data to Firestore (best-effort: don't fail if rules are not deployed yet)
      try {
        await _firestore.collection('feeChallans').doc(challanId).set({
          ...challanData,
          'createdAt': FieldValue.serverTimestamp(),
          'updatedAt': FieldValue.serverTimestamp(),
        });
      } catch (e) {
        debugPrint('[PdfChallanService] Warning: Could not save to feeChallans: $e');
      }

      final downloadUrl = await _uploadChallanText(challanId, challanText);

      // Update application with challan URL
      await _firestore
          .collection('hostelApplications')
          .doc(application.id)
          .update({
        'feeChallanUrl': downloadUrl,
        'status': 'fee_challan_generated',
        'updatedAt': FieldValue.serverTimestamp(),
      });

      return downloadUrl;
    } catch (e) {
      throw Exception('Failed to generate fee challan: $e');
    }
  }

  String _generateChallanText(Map<String, dynamic> data) {
    final dueDate = DateTime.parse(data['dueDate'] as String);
    final formattedDueDate = '${dueDate.day}/${dueDate.month}/${dueDate.year}';

    // Plain ASCII template to avoid encoding issues when viewed/downloaded
    final generatedAt =
        DateTime.parse(data['generatedAt'] as String).toString().split('.')[0];

    return '''
------------------------------------------------------------
                     HOSTEL FEE CHALLAN
------------------------------------------------------------
Application ID : ${data['applicationId']}
Student Name   : ${data['studentName']}
ARN/Roll Number: ${data['arnRollNumber']}
Email          : ${data['studentEmail']}
Room Type      : ${data['roomType'].toString().toUpperCase()}
------------------------------------------------------------
Fee Amount : PKR ${(data['feeAmount'] ?? 0).toStringAsFixed(2)}
Due Date   : $formattedDueDate
Generated  : $generatedAt
------------------------------------------------------------
PAYMENT DETAILS
Bank Name     : ${data['bankName']}
Account Number: ${data['accountNumber']}
Account Title : ${data['accountTitle']}
------------------------------------------------------------
Instructions:
1) Pay the above amount to the bank account mentioned above.
2) Take a screenshot of the payment receipt.
3) Upload payment proof in the Payments section.
4) Wait for admin confirmation.
------------------------------------------------------------
Status: ${data['status'].toString().toUpperCase()}
Generated by Smart Hostel Management System
------------------------------------------------------------
''';
  }

  /// Get challan for an application
  Future<Map<String, dynamic>?> getChallan(String applicationId) async {
    try {
      final doc =
          await _firestore.collection('feeChallans').doc(applicationId).get();

      if (doc.exists) {
        final data = doc.data()!;
        data['id'] = doc.id;
        return data;
      }
      return null;
    } catch (e) {
      throw Exception('Failed to get challan: $e');
    }
  }

  Future<String> _uploadChallanText(
      String challanId, String challanText) async {
    // On web we cannot use dart:io temporary files. Create an XFile from bytes instead.
    if (kIsWeb) {
      final bytes = utf8.encode(challanText);
      final uint8 = Uint8List.fromList(bytes);
      final xfile = XFile.fromData(
        uint8,
        name: '$challanId.txt',
        mimeType: 'text/plain',
      );
      final url = await CloudinaryService.uploadImage(
        file: xfile,
        resourceType: 'raw',
      );
      if (url == null) throw Exception('Challan upload cancelled');
      return url;
    }

    // Mobile/desktop: use platform-specific implementation
    return platform.uploadChallanFromFile(challanId, challanText);
  }
}

final pdfChallanServiceProvider = Provider<PdfChallanService>((ref) {
  return PdfChallanService();
});
